#!/bin/sh

export DANGER_PRICE_STOP_PERCENT=9
export IND_CHECK=rsi,bbands
export DYNAMIC_OFFexport_ORDERS=true
export DYNAMIC_exportTINGS_TIME=true
export EXCHANGE=bittrex
export MIN_SIZE_ORDER=0.025
export SIZE_FIRST_ORDERS=10%%
export BALANCE_COIN=10
export BALANCE_COIN_TWO=100
export EXCHANGE_FEE=0.20
export NAME_COIN=BTC
export NAME_COIN_TWO=ETH
export DEPOSIT_LIMIT=100%%
export ONE_ORDERS_SELL=false
export ONE_ORDERS_BUY=false
export BBANDS=true
export TYPE_SCALPER=1
export FIRST_LOADING_HISTORY=true
export ONE_ORDERS_PROFIT_PERCENT=0.2/100
export ONE_ORDERS_OFFexport=0.2
export OFFexport_FIRST_ORDERS_PERCENT=0.1
export OFFexport_ORDERS_PERCENT=0.2
export COUNT_ORDERS=20
export QUANTITY_ORDERS_IN_BLOCKS=10
export SIZE_ORDERS_MARTINGALE=30%%
export ONE_ORDERS_SPO_PERCENT=5
export AUTO_EXIT_PERCENT=10
export STOP_LOSS_FLOATING=10
export SIZE_FIRST_ORDERS=0.025
export IGNORE_ORDERS_AT_START=false
export TYPE_DATA_USED=active
export SAVE_HISTORY=false
export STOP_LOSS_ABS=5000
export GREEDY_FIRST_ORDER_SIZE=0
export STRATEGY_AUTO_REVERS=true
export TRAILING_STOP_PERCENT=0.4
export IS_PROFIT_INDICATORS=true
export DISABLE_CAPITALIZATION=true
export CAPITALIZATION_BUY_ORDER=true
export PARTIALLY_EXECUTED_GRID=true
export DANGER_PRICE_STOP=true
export FIRST_LOADING_HISTORY=true
export CONTINUE_MARTINGALE_GRID=false
export TREND_DEFINITION=true
export LOG=true
export LOG_DEBUG=false
export LOG_TRANSPORTS=0
export LANGUAGE=ru
export TIME_CLOSE_ORDERS=15
export TIME_CLOSE_ORDERS_INACTIVITY=60
export BBANDS_DEVIATION=0.7
export BBANDS_PERIOD=20
export RSI_RANGE_SELL=58/100
export RSI_RANGE_BUY=1/47
export RSI_PERIOD=12
export TIME_UPDATE_AUTO_exportTINGS=2




node ./build/server
